version: '3'
services:
  api:
    container_name: python-api
    restart: always
    build: .
    ports:
      - '26400:80'
    links:
      - mysql
  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./
      dockerfile: mysql.docker
    ports:
      - '26306:3306'
  order:
    container_name: order
    restart: always
    build:
      context: ./
      dockerfile: order.docker
    ports:
      - '26500:80'
    links:
      - api

  testorder:
    container_name: testorder
    restart: always
    build:
      context: ./
      dockerfile: testOrder.docker
    ports:
    - '26300:80'
    links:
    - order