version: '3'
services:
  app:
    container_name: python-api
    restart: always
    build: .
    ports:
      - '4000:80'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - backup.sql:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'Orders'
      MYSQL_ROOT_PASSWORD: 'Orders01'
    ports:
      - '3306:3306'