version: '3'
services:
  app:
    container_name: python-api
    restart: always
    build: .
    ports:
      - '4000:80'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'example'
    ports:
      - '3306:3306'