version: '3'
services:
  api:
    container_name: python-api
    restart: always
    build: .
    ports:
      - '26400:80'
    links:
      - mysql
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - ./:/etc/mysql/backup
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'Orders'
      MYSQL_ROOT_PASSWORD: 'Orders01'
    ports:
      - '26306:26306'
